### ISSUE TITLE
Double count of Wahlpflichtfächer

### ISSUE THREAD

**Issue by hekrause** [GoneUp/htwg-average-calculator#1]
Wahlpflichtfächer are counted twice:
![grafik](https://user-images.githubusercontent.com/17926729/37431855-b228a3d0-27d6-11e8-90ea-825b17e092ca.png)

![grafik](https://user-images.githubusercontent.com/17926729/37431882-c1953c3e-27d6-11e8-9353-f242582e218a.png)

**Comment by GoneUp** [comment]
Strange. I don't even got this subject in my report.

**Comment by GoneUp** [comment]
Quickfix: 22262 will also be filtered out.
